/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senac.pi.ui.janelas.atalhos;

import br.com.senac.pi.controlers.ClienteControler;
import br.com.senac.pi.model.entidades.Cliente;
import br.com.senac.pi.model.Dao.DaoCliente;
import br.com.senac.pi.ui.TelaFrenteDeCaixa;
import br.com.senac.factoryReposit.RepositorioroTabelaCliente;
import java.awt.Color;
import java.awt.Frame;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author jrneto
 */
public class TelaEditarClientes extends javax.swing.JDialog {

    private Cliente cliente;
    private Cliente clienteAntesDeEditar;

    private DaoCliente dao;
    private JTable tabela;
    private TelaFrenteDeCaixa caixa;
    private TelaDeCadastroDeCliente cadastroDeCliente;

    /**
     * Creates new form TelaEditarClientes
     * @param parent
     * @param modal
     * @param cliente
     * @param tabela
     * @param caixa
     * @param telaDeCadastroDeCliente
     */
    public TelaEditarClientes(
            java.awt.Frame parent,
            boolean modal, Cliente cliente,
            JTable tabela, TelaFrenteDeCaixa caixa,
            TelaDeCadastroDeCliente telaDeCadastroDeCliente) {
        
        super(parent, modal);

        initComponents();
        this.caixa = caixa;
        this.cadastroDeCliente = telaDeCadastroDeCliente;
        this.cliente = cliente;
        this.clienteAntesDeEditar = cliente;
        this.dao = new DaoCliente();
        this.tabela = tabela;

        prencheDadosCliente(cliente);
    }
    public TelaEditarClientes (java.awt.Frame parent,
            boolean modal){
        super(parent, modal);
     initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_salvar_cliente = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        btn_cancelar_editar_user = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        edit_txt_nome = new javax.swing.JTextField();
        edit_txt_cpf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_remover_cliente = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        btn_vincula_cliente_paraCompra = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 400));

        btn_salvar_cliente.setBackground(new java.awt.Color(51, 152, 219));
        btn_salvar_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_salvar_clienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_salvar_clienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_salvar_clienteMouseExited(evt);
            }
        });
        btn_salvar_cliente.setLayout(null);

        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones-ui/baseline_done_outline_white_18dp.png"))); // NOI18N
        btn_salvar_cliente.add(jLabel46);
        jLabel46.setBounds(10, 0, 40, 40);

        jLabel47.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Editar");
        btn_salvar_cliente.add(jLabel47);
        jLabel47.setBounds(50, 0, 60, 40);

        btn_cancelar_editar_user.setBackground(new java.awt.Color(51, 152, 219));
        btn_cancelar_editar_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cancelar_editar_userMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_cancelar_editar_userMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_cancelar_editar_userMouseExited(evt);
            }
        });
        btn_cancelar_editar_user.setLayout(null);

        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones-ui/baseline_cancel_white_18dp.png"))); // NOI18N
        btn_cancelar_editar_user.add(jLabel48);
        jLabel48.setBounds(10, 0, 40, 40);

        jLabel49.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Cancelar");
        btn_cancelar_editar_user.add(jLabel49);
        jLabel49.setBounds(50, 0, 60, 40);

        jLabel1.setText("Nome:");

        jLabel4.setText("CPF");

        btn_remover_cliente.setBackground(new java.awt.Color(51, 152, 219));
        btn_remover_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_remover_clienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_remover_clienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_remover_clienteMouseExited(evt);
            }
        });
        btn_remover_cliente.setLayout(null);

        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones-ui/baseline_warning_white_18dp.png"))); // NOI18N
        btn_remover_cliente.add(jLabel50);
        jLabel50.setBounds(10, 0, 40, 40);

        jLabel51.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Remover");
        btn_remover_cliente.add(jLabel51);
        jLabel51.setBounds(50, 0, 60, 40);

        btn_vincula_cliente_paraCompra.setBackground(new java.awt.Color(51, 152, 219));
        btn_vincula_cliente_paraCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_vincula_cliente_paraCompraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_vincula_cliente_paraCompraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_vincula_cliente_paraCompraMouseExited(evt);
            }
        });
        btn_vincula_cliente_paraCompra.setLayout(null);

        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones-ui/baseline_shopping_cart_white_18dp.png"))); // NOI18N
        btn_vincula_cliente_paraCompra.add(jLabel52);
        jLabel52.setBounds(10, 0, 40, 40);

        jLabel53.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("Vincular Cliente");
        btn_vincula_cliente_paraCompra.add(jLabel53);
        jLabel53.setBounds(60, 0, 120, 40);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edit_txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(edit_txt_cpf)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_salvar_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_remover_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_cancelar_editar_user, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_vincula_cliente_paraCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_vincula_cliente_paraCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edit_txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit_txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_salvar_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancelar_editar_user, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_remover_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salvar_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salvar_clienteMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        cliente.setNome(edit_txt_nome.getText());
        cliente.setCpf(edit_txt_cpf.getText());

        if (!clienteAntesDeEditar.equals(cliente)) {
            dao.deletar(clienteAntesDeEditar);
            dao.inserir(cliente);
        }
        int reply = JOptionPane.showConfirmDialog(null,
                "Deseja realmente editar esse cliente",
                "Editar cliente",
                JOptionPane.YES_NO_OPTION);

        if (reply == JOptionPane.YES_OPTION) {
            new RepositorioroTabelaCliente(tabela).atualizaTabela(dao.getAll());
            dispose();
        }


    }//GEN-LAST:event_btn_salvar_clienteMouseClicked
    private void prencheDadosCliente(Cliente cliente) {
        edit_txt_nome.setText(cliente.getNome());
        edit_txt_cpf.setText(cliente.getCpf());

    }
    private void btn_salvar_clienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salvar_clienteMouseEntered
        // TODO add your handling code here:
        btn_salvar_cliente.setBackground(new Color(119, 183, 225));//Cor quando entra no botton
    }//GEN-LAST:event_btn_salvar_clienteMouseEntered

    private void btn_salvar_clienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salvar_clienteMouseExited
        // TODO add your handling code here:
        btn_salvar_cliente.setBackground(new Color(51, 152, 219));//cor quando sai do botton
    }//GEN-LAST:event_btn_salvar_clienteMouseExited

    private void btn_cancelar_editar_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelar_editar_userMouseClicked
        // TODO add your handling code here:
        dispose();
        limpaCampos();
    }//GEN-LAST:event_btn_cancelar_editar_userMouseClicked
    private void limpaCampos() {
        edit_txt_cpf.setText("");

        edit_txt_nome.setText("");
    }
    private void btn_cancelar_editar_userMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelar_editar_userMouseEntered
        // TODO add your handling code here:
        btn_cancelar_editar_user.setBackground(new Color(119, 183, 225));//Cor quando entra no botton
    }//GEN-LAST:event_btn_cancelar_editar_userMouseEntered

    private void btn_cancelar_editar_userMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cancelar_editar_userMouseExited
        // TODO add your handling code here:
        btn_cancelar_editar_user.setBackground(new Color(51, 152, 219));//cor quando sai do botton
    }//GEN-LAST:event_btn_cancelar_editar_userMouseExited

    private void btn_remover_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_remover_clienteMouseClicked
        // TODO add your handling code here:    
        int reply = JOptionPane.showConfirmDialog(null,
                "Deseja remover Cliente",
                "Remover Cliente",
                JOptionPane.YES_NO_OPTION);

        if (reply == JOptionPane.YES_OPTION) {
            new ClienteControler(new RepositorioroTabelaCliente(tabela)).removeCleinte(cliente);
            dispose();
        }

    }//GEN-LAST:event_btn_remover_clienteMouseClicked

    private void btn_remover_clienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_remover_clienteMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_remover_clienteMouseEntered

    private void btn_remover_clienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_remover_clienteMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_remover_clienteMouseExited

    private void btn_vincula_cliente_paraCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_vincula_cliente_paraCompraMouseClicked
        // TODO add your handling code here:

        caixa.vinculaCliente(cliente);
        cadastroDeCliente.dispose();
        dispose();
        

    }//GEN-LAST:event_btn_vincula_cliente_paraCompraMouseClicked

    private void btn_vincula_cliente_paraCompraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_vincula_cliente_paraCompraMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_vincula_cliente_paraCompraMouseEntered

    private void btn_vincula_cliente_paraCompraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_vincula_cliente_paraCompraMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_vincula_cliente_paraCompraMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_cancelar_editar_user;
    private javax.swing.JPanel btn_remover_cliente;
    private javax.swing.JPanel btn_salvar_cliente;
    private javax.swing.JPanel btn_vincula_cliente_paraCompra;
    private javax.swing.JTextField edit_txt_cpf;
    private javax.swing.JTextField edit_txt_nome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
